#!/usr/bin/env node

// Command line tool. WIP.

//import compile from './compiler.js';

require('@std/esm');
var minimist = require( 'minimist' ),
  fs = require( 'fs' ),
  //compiler = require( './src/compiler.js' );
  compiler = require( './bundle.js' );
var argv = minimist( process.argv.slice( 2 ) );


function runCompile() {
  var title = argv.c,
    newTitle = argv.o || ( title.slice( 0, -( '.englsh'.length ) ) + '.js' );
  if ( title.endsWith( '.englsh') ) {
    var source = fs.readFileSync( title, 'utf8' ),
      jsCode = compiler.compile( source ).code,
      header = '// Generated by englsh.js\n';
      resultContent = header + jsCode;

    // TODO: Sourcemaps.
    console.log( 'Translating to code...' );
    fs.writeFile( newTitle, resultContent, error => {
      if ( error ) {
        throw error;
      } else {
        console.log( `${ title } > ${ newTitle } , complete.` );
      }
    } );
  } else {
    throw new Error( 'Wrong filetype: Should be .englsh' );
  }
}

if ( argv.c ) {
  runCompile();
}
